// <auto-generated />
using System;
using AutoFix.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoFix.Migrations.Servico
{
    [DbContext(typeof(ServicoContext))]
    partial class ServicoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutoFix.Models.Motorista", b =>
                {
                    b.Property<int>("IdMotorista")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMotorista"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMotorista");

                    b.ToTable("Motorista");
                });

            modelBuilder.Entity("AutoFix.Models.PrestadorServico", b =>
                {
                    b.Property<int>("IdPrestador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPrestador"));

                    b.Property<double>("Avaliacao")
                        .HasColumnType("float");

                    b.Property<string>("Bairro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HrFunc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logradouro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Senha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPrestador");

                    b.ToTable("PrestadorServico");
                });

            modelBuilder.Entity("AutoFix.Models.Servico", b =>
                {
                    b.Property<int>("IdServico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdServico"));

                    b.Property<double>("Avaliacao")
                        .HasColumnType("float");

                    b.Property<DateTime>("HrSolicitacao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdMotorista")
                        .HasColumnType("int");

                    b.Property<int?>("IdPrestador")
                        .HasColumnType("int");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.HasKey("IdServico");

                    b.HasIndex("IdMotorista");

                    b.HasIndex("IdPrestador");

                    b.ToTable("Servicos");
                });

            modelBuilder.Entity("AutoFix.Models.Servico", b =>
                {
                    b.HasOne("AutoFix.Models.Motorista", "Motorista")
                        .WithMany()
                        .HasForeignKey("IdMotorista");

                    b.HasOne("AutoFix.Models.PrestadorServico", "Prestador")
                        .WithMany()
                        .HasForeignKey("IdPrestador");

                    b.Navigation("Motorista");

                    b.Navigation("Prestador");
                });
#pragma warning restore 612, 618
        }
    }
}
